services:
  pg:
    image: postgres:16-alpine
    container_name: remain_local_db
    environment:
      POSTGRES_DB: business_planner
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cVlgX2PgrIXKk0gRqQmebQ
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d business_planner"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer
    container_name: remain_local_adminer
    ports:
      - "8080:8080"
    depends_on:
      - pg

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: remain_local_api
    env_file:
      - .env.local
    depends_on:
      pg:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: remain_local_frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  pg_data:
