"""calendar_notify_and_notifications

Revision ID: d512983fa450
Revises: 00e0591122d1
Create Date: 2026-06-11 18:39:22.963062

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d512983fa450"
down_revision: str | Sequence[str] | None = "00e0591122d1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "source_type",
            sa.String(length=50),
            nullable=False,
            comment="calendar_event | tax_event",
        ),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        op.f("ix_notifications_user_id"),
        "notifications",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_block_tags_tag_id"), table_name="block_tags")
    op.drop_index(op.f("ix_business_plans_user_id"), table_name="business_plans")
    op.add_column(
        "calendar_events",
        sa.Column(
            "notify_before",
            sa.Integer(),
            nullable=True,
            comment="За сколько минут до события уведомить",
        ),
    )
    op.add_column(
        "calendar_events",
        sa.Column(
            "notified_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Когда было отправлено уведомление",
        ),
    )
    op.drop_index(op.f("ix_calendar_events_user_date"), table_name="calendar_events")
    op.drop_index(op.f("ix_chart_points_chart_id"), table_name="chart_points")
    op.drop_index(op.f("ix_note_tags_tag_id"), table_name="note_tags")
    op.drop_index(op.f("ix_notes_user_updated"), table_name="notes")
    op.drop_index(op.f("ix_plan_tags_tag_id"), table_name="plan_tags")
    # avatar_url was removed from the model; drop if it still exists
    conn = op.get_bind()
    result = conn.execute(
        sa.text("SELECT column_name FROM information_schema.columns WHERE table_name='users' AND column_name='avatar_url'")
    )
    if result.fetchone():
        op.drop_column("users", "avatar_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "avatar_url",
            sa.VARCHAR(length=500),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(op.f("ix_plan_tags_tag_id"), "plan_tags", ["tag_id"], unique=False)
    op.create_index(
        op.f("ix_notes_user_updated"),
        "notes",
        ["user_id", "updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_note_tags_tag_id"), "note_tags", ["tag_id"], unique=False)
    op.create_index(
        op.f("ix_chart_points_chart_id"),
        "chart_points",
        ["chart_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_calendar_events_user_date"),
        "calendar_events",
        ["user_id", "event_date"],
        unique=False,
    )
    op.drop_column("calendar_events", "notified_at")
    op.drop_column("calendar_events", "notify_before")
    op.create_index(
        op.f("ix_business_plans_user_id"),
        "business_plans",
        ["user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_block_tags_tag_id"), "block_tags", ["tag_id"], unique=False)
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    # ### end Alembic commands ###
