"""add_snapshots_comments_and_public_sharing

Revision ID: 2f8703357c5a
Revises: cedb05384afc
Create Date: 2026-05-18 23:31:38.118623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f8703357c5a"
down_revision: str | Sequence[str] | None = "cedb05384afc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_snapshots",
        sa.Column("business_plan_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=False),
        sa.Column(
            "blocks_snapshot",
            sa.JSON(),
            server_default=sa.text("'[]'::json"),
            nullable=False,
        ),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["business_plan_id"],
            ["business_plans.id"],
            name=op.f("fk_plan_snapshots_business_plan_id_business_plans"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
            name=op.f("fk_plan_snapshots_created_by_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_snapshots")),
    )
    op.create_index(
        op.f("ix_plan_snapshots_business_plan_id"),
        "plan_snapshots",
        ["business_plan_id"],
        unique=False,
    )
    op.create_table(
        "block_comments",
        sa.Column("plan_block_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("NOW()"),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_block_id"],
            ["plan_blocks.id"],
            name=op.f("fk_block_comments_plan_block_id_plan_blocks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_block_comments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_block_comments")),
    )
    op.create_index(
        op.f("ix_block_comments_plan_block_id"),
        "block_comments",
        ["plan_block_id"],
        unique=False,
    )
    op.add_column(
        "business_plans",
        sa.Column("share_token", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "business_plans",
        sa.Column("is_public", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_index(
        op.f("ix_business_plans_share_token"),
        "business_plans",
        ["share_token"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_business_plans_share_token"), table_name="business_plans")
    op.drop_column("business_plans", "is_public")
    op.drop_column("business_plans", "share_token")
    op.drop_index(op.f("ix_block_comments_plan_block_id"), table_name="block_comments")
    op.drop_table("block_comments")
    op.drop_index(op.f("ix_plan_snapshots_business_plan_id"), table_name="plan_snapshots")
    op.drop_table("plan_snapshots")
    # ### end Alembic commands ###
